apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: context-memory
resources:
  - deployment.yaml
commonLabels:
  app.kubernetes.io/name: context-memory
  app.kubernetes.io/part-of: context-memory
  app.kubernetes.io/managed-by: kustomize
images:
  - name: ghcr.io/devopstrio/context-memory
    newTag: latest
